apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app
  namespace: default
  labels:
    app: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  endpoints:
  - port: metrics
